### ISSUE TITLE
Accuracy too low :(

### ISSUE THREAD

**Issue by JoseLavariega** [leggedrobotics/plr-exercise#5]
![image](https://github.com/leggedrobotics/plr-exercise/assets/21208974/f8995b42-21db-4a0d-8cca-99af0433ec41)
Upon running the unedited code, the accuracy over MNIST is of 11%, which is very close to random indeed.

**Comment by JonasFrey96** [comment]
@JoseLavariega, thanks for opening up the issue here - Please also open up the same issue on your fork of the repository.
